name: cav1_bridge
from_domain: 1
to_domain: 2
topics:
  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 2
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 2

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 3
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 3

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 4
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 4

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 5
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 5

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 6
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 6

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 7
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 7

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 8
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 8

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 9
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 9

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 10
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 10

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 11
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 11

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 12
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 12

  Ego_pose:
    type: geometry_msgs/msg/PoseStamped
    reliability: best_effort
    remap: /CAV1_pose
    to_domain: 31
  cmd_vel:
    type: geometry_msgs/msg/Twist
    reliability: best_effort
    remap: /CAV1_cmd_vel
    to_domain: 31
